# Generated by Django 5.1.1 on 2024-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sponsor_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
